/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package css.specificity

fun main() {
    println(getSpecificity("*"))
}

typealias Specificity = Triple<Int, Int, Int>

private val delimiter = """[\s>+~]+""".toRegex()

fun getSpecificity(selector: String): Specificity {
    val specificity = selector.trim().split(delimiter).fold(Specificity(0, 0, 0)) {
        acc, subSelector -> acc.add(valueOf(subSelector.trim()))
    }

    return specificity
}

fun valueOf(selector: String): Specificity = when {
    selector == "*" -> Specificity(0, 0, 0)
    isClass(selector) -> Specificity(0, 1, 0)
    else -> Specificity(0, 0, 1)
}

fun isClass(selector: String): Boolean = selector.startsWith(".")

fun Specificity.add(other: Specificity): Specificity {
    return Specificity(
        this.first + other.first,
        this.second + other.second,
        this.third + other.third,
    )
}