/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package css.specificity

fun main() {
    println(getSpecificity("*"))
}

fun getSpecificity(selector: String) = Triple(0,0,0)
